//Register
export const AUTH_START_USER_REGISTER_OTP = 'AUTH_START_USER_REGISTER_OTP';
export const AUTH_START_USER_REGISTER_OTP_SUCCESS = 'AUTH_START_USER_REGISTER_OTP_SUCCESS';
export const AUTH_USER_REGISTER_OTP_FAIL_OTP = 'AUTH_USER_REGISTER_OTP_FAIL_OTP';
export const Auth_USER_OTP_SUCCESS = 'Auth_USER_OTP_SUCCESS';

//LOGIN
export const AUTH_START_USER = 'AUTH_START_USER';
export const AUTH_SUCCESS_USER = 'AUTH_SUCCESS_USER';
export const AUTH_FAIL_USER = 'AUTH_FAIL_USER';
export const AUTH_USER_USER = 'AUTH_USER_USER';
export const AUTH_LOGOUT_USER = 'AUTH_LOGOUT_USER';

//REGISTER USER

export const REGISTER_USER_START = 'REGISTER_USER_START';
export const REGISTER_USER_OTP_SEND = 'REGISTER_USER_OTP_SEND';
export const REGISTER_USER_OTP_FAIL = 'REGISTER_USER_OTP_FAIL';

//OTP VERIFY

export const OTP_USER_START = 'OTP_USER_START';
export const OTP_USER_OTP_SUCCESS = 'OTP_USER_SUCCESS';
export const OTP_FAIL = 'OTP_USER_FAIL';

//LOGIN WITH OTP
export const LOGIN_OTP_START = 'LOGIN_OTP_START';
export const LOGIN_OTP_SEND = 'LOGIN_OTP_SEND';
export const LOGIN_OTP_FAIL = 'LOGIN_OTP_FAIL';

//LOGIN OTP VERIFY
export const LOGIN_OTP_VERIFY_START = 'LOGIN_OTP_VERIFY_START';
export const LOGIN_OTP_VERIFY_SUCCESS = 'LOGIN_OTP_VERIFY_SUCCESS';
export const LOGIN_OTP_VERIFY_FAIL = 'LOGIN_OTP_VERIFY_FAIL';
