export const AUTH_START_DEALER = 'AUTH_START_DEALER';
export const AUTH_SUCCESS_DEALER = 'AUTH_SUCCESS_DEALER';
export const AUTH_FAIL_DEALER = 'AUTH_FAIL_DEALER';
export const AUTH_USER_DEALER = 'AUTH_USER_DEALER';
export const AUTH_LOGOUT_DEALER = 'AUTH_LOGOUT_DEALER';
